### ISSUE TITLE
Project Description

### ISSUE THREAD

**Issue by mehmetsefabalik** [gitftp/gitftp#1]
Can you provide a project description? This way, community can see your purpose and can help you.

**Comment by craftpip** [comment]
A git deployment tool, 
commit and push on GIT, and this software will deploy the right version to the servers.

I made a version of this 2 years back, which was self-hosted, i decided now to remake and open-source it.
Its a tool like ftploy, beanstalkapp but open source.

**Comment by craftpip** [comment]
features: 
* Will use your oAuth app, to connect to github or bitbucket
* Deploy to multiple servers, setup environments
* servers are FTP, SFTP, or LOCAL (if the deployment is to be done on the same server)
* Config files for servers - to insert variables into files, such as database details.
* and much more.

**Comment by mehmetsefabalik** [comment]
Interesting project, can you create a more descriptive wiki for that?

**Comment by craftpip** [comment]
Alright, sure I'll do that.
